/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 130
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 70
#define ALIAS_COUNT 0
#define TOKEN_COUNT 35
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 14
#define MAX_ALIAS_SEQUENCE_LENGTH 10
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 20
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_plain_identifier = 1,
  anon_sym_LPAREN = 2,
  anon_sym_RPAREN = 3,
  anon_sym_COLON = 4,
  anon_sym_EQ = 5,
  anon_sym_SEMI = 6,
  anon_sym_in = 7,
  anon_sym_out = 8,
  anon_sym_signal = 9,
  anon_sym_float = 10,
  anon_sym_int = 11,
  anon_sym_bang = 12,
  anon_sym_list = 13,
  anon_sym_symbol = 14,
  anon_sym_wire = 15,
  anon_sym_COMMA = 16,
  anon_sym_msg = 17,
  anon_sym_DOTattr_LPAREN = 18,
  anon_sym_LBRACK = 19,
  anon_sym_RBRACK = 20,
  anon_sym_feedback = 21,
  anon_sym_state = 22,
  anon_sym_DOT = 23,
  sym_operator_name = 24,
  sym_tilde_identifier = 25,
  sym_dotted_segment = 26,
  sym_integer = 27,
  aux_sym_number_token1 = 28,
  aux_sym_number_token2 = 29,
  aux_sym_number_token3 = 30,
  aux_sym_number_token4 = 31,
  aux_sym_number_token5 = 32,
  sym_string = 33,
  sym_comment = 34,
  sym_source_file = 35,
  sym__statement = 36,
  sym_port_declaration = 37,
  sym_direction = 38,
  sym_type_name = 39,
  sym_destructuring_wire = 40,
  sym_identifier_list = 41,
  sym_wire_declaration = 42,
  sym_msg_declaration = 43,
  sym_attr_chain = 44,
  sym_attr_list = 45,
  sym_attr_pair = 46,
  sym__attr_value = 47,
  sym_out_assignment = 48,
  sym_direct_connection = 49,
  sym_feedback_declaration = 50,
  sym_feedback_assignment = 51,
  sym_state_declaration = 52,
  sym_state_assignment = 53,
  sym_control_type = 54,
  sym_input_port_access = 55,
  sym_output_port_access = 56,
  sym__expression = 57,
  sym_tuple_expression = 58,
  sym_object_call = 59,
  sym_object_name = 60,
  sym_argument_list = 61,
  sym_identifier = 62,
  sym_dotted_identifier = 63,
  sym_number = 64,
  aux_sym_source_file_repeat1 = 65,
  aux_sym_identifier_list_repeat1 = 66,
  aux_sym_attr_list_repeat1 = 67,
  aux_sym_tuple_expression_repeat1 = 68,
  aux_sym_dotted_identifier_repeat1 = 69,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_plain_identifier] = "plain_identifier",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COLON] = ":",
  [anon_sym_EQ] = "=",
  [anon_sym_SEMI] = ";",
  [anon_sym_in] = "in",
  [anon_sym_out] = "out",
  [anon_sym_signal] = "signal",
  [anon_sym_float] = "float",
  [anon_sym_int] = "int",
  [anon_sym_bang] = "bang",
  [anon_sym_list] = "list",
  [anon_sym_symbol] = "symbol",
  [anon_sym_wire] = "wire",
  [anon_sym_COMMA] = ",",
  [anon_sym_msg] = "msg",
  [anon_sym_DOTattr_LPAREN] = ".attr(",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_feedback] = "feedback",
  [anon_sym_state] = "state",
  [anon_sym_DOT] = ".",
  [sym_operator_name] = "operator_name",
  [sym_tilde_identifier] = "tilde_identifier",
  [sym_dotted_segment] = "dotted_segment",
  [sym_integer] = "integer",
  [aux_sym_number_token1] = "number_token1",
  [aux_sym_number_token2] = "number_token2",
  [aux_sym_number_token3] = "number_token3",
  [aux_sym_number_token4] = "number_token4",
  [aux_sym_number_token5] = "number_token5",
  [sym_string] = "string",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_port_declaration] = "port_declaration",
  [sym_direction] = "direction",
  [sym_type_name] = "type_name",
  [sym_destructuring_wire] = "destructuring_wire",
  [sym_identifier_list] = "identifier_list",
  [sym_wire_declaration] = "wire_declaration",
  [sym_msg_declaration] = "msg_declaration",
  [sym_attr_chain] = "attr_chain",
  [sym_attr_list] = "attr_list",
  [sym_attr_pair] = "attr_pair",
  [sym__attr_value] = "_attr_value",
  [sym_out_assignment] = "out_assignment",
  [sym_direct_connection] = "direct_connection",
  [sym_feedback_declaration] = "feedback_declaration",
  [sym_feedback_assignment] = "feedback_assignment",
  [sym_state_declaration] = "state_declaration",
  [sym_state_assignment] = "state_assignment",
  [sym_control_type] = "control_type",
  [sym_input_port_access] = "input_port_access",
  [sym_output_port_access] = "output_port_access",
  [sym__expression] = "_expression",
  [sym_tuple_expression] = "tuple_expression",
  [sym_object_call] = "object_call",
  [sym_object_name] = "object_name",
  [sym_argument_list] = "argument_list",
  [sym_identifier] = "identifier",
  [sym_dotted_identifier] = "dotted_identifier",
  [sym_number] = "number",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_identifier_list_repeat1] = "identifier_list_repeat1",
  [aux_sym_attr_list_repeat1] = "attr_list_repeat1",
  [aux_sym_tuple_expression_repeat1] = "tuple_expression_repeat1",
  [aux_sym_dotted_identifier_repeat1] = "dotted_identifier_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_plain_identifier] = sym_plain_identifier,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_out] = anon_sym_out,
  [anon_sym_signal] = anon_sym_signal,
  [anon_sym_float] = anon_sym_float,
  [anon_sym_int] = anon_sym_int,
  [anon_sym_bang] = anon_sym_bang,
  [anon_sym_list] = anon_sym_list,
  [anon_sym_symbol] = anon_sym_symbol,
  [anon_sym_wire] = anon_sym_wire,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_msg] = anon_sym_msg,
  [anon_sym_DOTattr_LPAREN] = anon_sym_DOTattr_LPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_feedback] = anon_sym_feedback,
  [anon_sym_state] = anon_sym_state,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_operator_name] = sym_operator_name,
  [sym_tilde_identifier] = sym_tilde_identifier,
  [sym_dotted_segment] = sym_dotted_segment,
  [sym_integer] = sym_integer,
  [aux_sym_number_token1] = aux_sym_number_token1,
  [aux_sym_number_token2] = aux_sym_number_token2,
  [aux_sym_number_token3] = aux_sym_number_token3,
  [aux_sym_number_token4] = aux_sym_number_token4,
  [aux_sym_number_token5] = aux_sym_number_token5,
  [sym_string] = sym_string,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_port_declaration] = sym_port_declaration,
  [sym_direction] = sym_direction,
  [sym_type_name] = sym_type_name,
  [sym_destructuring_wire] = sym_destructuring_wire,
  [sym_identifier_list] = sym_identifier_list,
  [sym_wire_declaration] = sym_wire_declaration,
  [sym_msg_declaration] = sym_msg_declaration,
  [sym_attr_chain] = sym_attr_chain,
  [sym_attr_list] = sym_attr_list,
  [sym_attr_pair] = sym_attr_pair,
  [sym__attr_value] = sym__attr_value,
  [sym_out_assignment] = sym_out_assignment,
  [sym_direct_connection] = sym_direct_connection,
  [sym_feedback_declaration] = sym_feedback_declaration,
  [sym_feedback_assignment] = sym_feedback_assignment,
  [sym_state_declaration] = sym_state_declaration,
  [sym_state_assignment] = sym_state_assignment,
  [sym_control_type] = sym_control_type,
  [sym_input_port_access] = sym_input_port_access,
  [sym_output_port_access] = sym_output_port_access,
  [sym__expression] = sym__expression,
  [sym_tuple_expression] = sym_tuple_expression,
  [sym_object_call] = sym_object_call,
  [sym_object_name] = sym_object_name,
  [sym_argument_list] = sym_argument_list,
  [sym_identifier] = sym_identifier,
  [sym_dotted_identifier] = sym_dotted_identifier,
  [sym_number] = sym_number,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_identifier_list_repeat1] = aux_sym_identifier_list_repeat1,
  [aux_sym_attr_list_repeat1] = aux_sym_attr_list_repeat1,
  [aux_sym_tuple_expression_repeat1] = aux_sym_tuple_expression_repeat1,
  [aux_sym_dotted_identifier_repeat1] = aux_sym_dotted_identifier_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_plain_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_out] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_signal] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_float] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_int] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bang] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_list] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_symbol] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_wire] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_msg] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOTattr_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_feedback] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_state] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_operator_name] = {
    .visible = true,
    .named = true,
  },
  [sym_tilde_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_dotted_segment] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_number_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_number_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_number_token3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_number_token4] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_number_token5] = {
    .visible = false,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_port_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_direction] = {
    .visible = true,
    .named = true,
  },
  [sym_type_name] = {
    .visible = true,
    .named = true,
  },
  [sym_destructuring_wire] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier_list] = {
    .visible = true,
    .named = true,
  },
  [sym_wire_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_msg_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_attr_chain] = {
    .visible = true,
    .named = true,
  },
  [sym_attr_list] = {
    .visible = true,
    .named = true,
  },
  [sym_attr_pair] = {
    .visible = true,
    .named = true,
  },
  [sym__attr_value] = {
    .visible = false,
    .named = true,
  },
  [sym_out_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_direct_connection] = {
    .visible = true,
    .named = true,
  },
  [sym_feedback_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_feedback_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_state_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_state_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_control_type] = {
    .visible = true,
    .named = true,
  },
  [sym_input_port_access] = {
    .visible = true,
    .named = true,
  },
  [sym_output_port_access] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_tuple_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_object_call] = {
    .visible = true,
    .named = true,
  },
  [sym_object_name] = {
    .visible = true,
    .named = true,
  },
  [sym_argument_list] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_dotted_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_identifier_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_attr_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tuple_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dotted_identifier_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_arguments = 1,
  field_attrs = 2,
  field_content = 3,
  field_direction = 4,
  field_index = 5,
  field_init = 6,
  field_key = 7,
  field_name = 8,
  field_names = 9,
  field_object = 10,
  field_pairs = 11,
  field_target = 12,
  field_type = 13,
  field_value = 14,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_arguments] = "arguments",
  [field_attrs] = "attrs",
  [field_content] = "content",
  [field_direction] = "direction",
  [field_index] = "index",
  [field_init] = "init",
  [field_key] = "key",
  [field_name] = "name",
  [field_names] = "names",
  [field_object] = "object",
  [field_pairs] = "pairs",
  [field_target] = "target",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 2},
  [5] = {.index = 7, .length = 2},
  [6] = {.index = 9, .length = 2},
  [7] = {.index = 11, .length = 3},
  [8] = {.index = 14, .length = 3},
  [9] = {.index = 17, .length = 3},
  [10] = {.index = 20, .length = 2},
  [11] = {.index = 22, .length = 2},
  [12] = {.index = 24, .length = 2},
  [13] = {.index = 26, .length = 2},
  [14] = {.index = 28, .length = 1},
  [15] = {.index = 29, .length = 3},
  [16] = {.index = 32, .length = 4},
  [17] = {.index = 36, .length = 2},
  [18] = {.index = 38, .length = 4},
  [19] = {.index = 42, .length = 5},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_object, 0},
  [1] =
    {field_target, 0},
    {field_value, 2},
  [3] =
    {field_name, 1},
    {field_value, 3},
  [5] =
    {field_content, 3},
    {field_name, 1},
  [7] =
    {field_name, 1},
    {field_type, 3},
  [9] =
    {field_target, 1},
    {field_value, 3},
  [11] =
    {field_direction, 0},
    {field_name, 1},
    {field_type, 3},
  [14] =
    {field_attrs, 4},
    {field_name, 1},
    {field_value, 3},
  [17] =
    {field_attrs, 4},
    {field_content, 3},
    {field_name, 1},
  [20] =
    {field_index, 4},
    {field_object, 0},
  [22] =
    {field_arguments, 2},
    {field_object, 0},
  [24] =
    {field_index, 2},
    {field_value, 5},
  [26] =
    {field_names, 2},
    {field_value, 5},
  [28] =
    {field_pairs, 1},
  [29] =
    {field_init, 5},
    {field_name, 1},
    {field_type, 3},
  [32] =
    {field_direction, 0},
    {field_name, 1},
    {field_type, 3},
    {field_value, 5},
  [36] =
    {field_key, 0},
    {field_value, 2},
  [38] =
    {field_direction, 0},
    {field_index, 1},
    {field_name, 3},
    {field_type, 6},
  [42] =
    {field_direction, 0},
    {field_index, 1},
    {field_name, 3},
    {field_type, 6},
    {field_value, 8},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 38,
  [40] = 40,
  [41] = 41,
  [42] = 35,
  [43] = 36,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 41,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 67,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 83,
  [127] = 127,
  [128] = 128,
  [129] = 129,
};

static const TSCharacterRange sym_tilde_identifier_character_set_1[] = {
  {'!', '!'}, {'%', '&'}, {'*', '+'}, {'-', '-'}, {'/', '9'}, {'<', '>'}, {'A', 'Z'}, {'^', '_'},
  {'a', 'z'}, {'|', '|'},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(23);
      ADVANCE_MAP(
        '"', 3,
        '(', 24,
        ')', 25,
        ',', 31,
        '-', 16,
        '.', 36,
        '/', 10,
        ':', 26,
        ';', 28,
        '=', 27,
        '[', 33,
        ']', 34,
        'o', 47,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(50);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '"', 3,
        '(', 24,
        ')', 25,
        ',', 31,
        '-', 16,
        '.', 35,
        '/', 10,
        ';', 28,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(56);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '(') ADVANCE(24);
      if (lookahead == ')') ADVANCE(25);
      if (lookahead == '-') ADVANCE(38);
      if (lookahead == '/') ADVANCE(37);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(56);
      if (lookahead == '!' ||
          lookahead == '%' ||
          lookahead == '&' ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('<' <= lookahead && lookahead <= '?') ||
          lookahead == '^' ||
          lookahead == '|') ADVANCE(39);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(57);
      if (lookahead == '\\') ADVANCE(22);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '(') ADVANCE(32);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(6);
      if (lookahead == '.') ADVANCE(21);
      if (lookahead == '~') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 6:
      if (lookahead == '.') ADVANCE(21);
      if (lookahead == '~') ADVANCE(41);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(10);
      if (lookahead == '[') ADVANCE(33);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 8:
      if (lookahead == '/') ADVANCE(10);
      if (lookahead == 'o') ADVANCE(43);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 9:
      if (lookahead == '/') ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(9);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 10:
      if (lookahead == '/') ADVANCE(58);
      END_STATE();
    case 11:
      if (lookahead == 'r') ADVANCE(4);
      END_STATE();
    case 12:
      if (lookahead == 't') ADVANCE(11);
      END_STATE();
    case 13:
      if (lookahead == 't') ADVANCE(12);
      END_STATE();
    case 14:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(53);
      END_STATE();
    case 15:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      END_STATE();
    case 16:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(56);
      END_STATE();
    case 17:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(53);
      END_STATE();
    case 18:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      END_STATE();
    case 19:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 20:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 21:
      if (set_contains(sym_tilde_identifier_character_set_1, 10, lookahead)) ADVANCE(6);
      END_STATE();
    case 22:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_out);
      if (lookahead == '-') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_out);
      if (lookahead == '-') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_DOTattr_LPAREN);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (lookahead == 'a') ADVANCE(13);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_operator_name);
      if (lookahead == '/') ADVANCE(40);
      if (lookahead == '!' ||
          lookahead == '%' ||
          lookahead == '&' ||
          lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '-' ||
          ('<' <= lookahead && lookahead <= '?') ||
          lookahead == '^' ||
          lookahead == '|') ADVANCE(39);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_operator_name);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(56);
      if ((set_contains(sym_tilde_identifier_character_set_1, 10, lookahead) ||
          lookahead == '?') &&
          (lookahead < 'A' || 'Z' < lookahead) &&
          lookahead != '_' &&
          (lookahead < 'a' || 'z' < lookahead)) ADVANCE(39);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_operator_name);
      if ((set_contains(sym_tilde_identifier_character_set_1, 10, lookahead) ||
          lookahead == '?') &&
          (lookahead < '0' || '9' < lookahead) &&
          (lookahead < 'A' || 'Z' < lookahead) &&
          lookahead != '_' &&
          (lookahead < 'a' || 'z' < lookahead)) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_operator_name);
      if ((set_contains(sym_tilde_identifier_character_set_1, 10, lookahead) ||
          lookahead == '?') &&
          (lookahead < '0' || '9' < lookahead) &&
          (lookahead < 'A' || 'Z' < lookahead) &&
          lookahead != '_' &&
          (lookahead < 'a' || 'z' < lookahead)) ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(58);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_tilde_identifier);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_dotted_segment);
      if (lookahead == '-') ADVANCE(20);
      if (lookahead == 't') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_dotted_segment);
      if (lookahead == '-') ADVANCE(20);
      if (lookahead == 'u') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_dotted_segment);
      if (lookahead == '-') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_dotted_segment);
      if (lookahead == '-') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '=' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_plain_identifier);
      if (lookahead == '-') ADVANCE(19);
      if (lookahead == 't') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_plain_identifier);
      if (lookahead == '-') ADVANCE(19);
      if (lookahead == 'u') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_plain_identifier);
      if (lookahead == '-') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_plain_identifier);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == '.') ADVANCE(21);
      if (lookahead == '~') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(55);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_number_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_number_token2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(53);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_number_token3);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_number_token4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(54);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_number_token5);
      if (lookahead == '.') ADVANCE(55);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(58);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'b') ADVANCE(1);
      if (lookahead == 'f') ADVANCE(2);
      if (lookahead == 'i') ADVANCE(3);
      if (lookahead == 'l') ADVANCE(4);
      if (lookahead == 'm') ADVANCE(5);
      if (lookahead == 's') ADVANCE(6);
      if (lookahead == 'w') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'a') ADVANCE(8);
      END_STATE();
    case 2:
      if (lookahead == 'e') ADVANCE(9);
      if (lookahead == 'l') ADVANCE(10);
      END_STATE();
    case 3:
      if (lookahead == 'n') ADVANCE(11);
      END_STATE();
    case 4:
      if (lookahead == 'i') ADVANCE(12);
      END_STATE();
    case 5:
      if (lookahead == 's') ADVANCE(13);
      END_STATE();
    case 6:
      if (lookahead == 'i') ADVANCE(14);
      if (lookahead == 't') ADVANCE(15);
      if (lookahead == 'y') ADVANCE(16);
      END_STATE();
    case 7:
      if (lookahead == 'i') ADVANCE(17);
      END_STATE();
    case 8:
      if (lookahead == 'n') ADVANCE(18);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(19);
      END_STATE();
    case 10:
      if (lookahead == 'o') ADVANCE(20);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_in);
      if (lookahead == 't') ADVANCE(21);
      END_STATE();
    case 12:
      if (lookahead == 's') ADVANCE(22);
      END_STATE();
    case 13:
      if (lookahead == 'g') ADVANCE(23);
      END_STATE();
    case 14:
      if (lookahead == 'g') ADVANCE(24);
      END_STATE();
    case 15:
      if (lookahead == 'a') ADVANCE(25);
      END_STATE();
    case 16:
      if (lookahead == 'm') ADVANCE(26);
      END_STATE();
    case 17:
      if (lookahead == 'r') ADVANCE(27);
      END_STATE();
    case 18:
      if (lookahead == 'g') ADVANCE(28);
      END_STATE();
    case 19:
      if (lookahead == 'd') ADVANCE(29);
      END_STATE();
    case 20:
      if (lookahead == 'a') ADVANCE(30);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_int);
      END_STATE();
    case 22:
      if (lookahead == 't') ADVANCE(31);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_msg);
      END_STATE();
    case 24:
      if (lookahead == 'n') ADVANCE(32);
      END_STATE();
    case 25:
      if (lookahead == 't') ADVANCE(33);
      END_STATE();
    case 26:
      if (lookahead == 'b') ADVANCE(34);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(35);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_bang);
      END_STATE();
    case 29:
      if (lookahead == 'b') ADVANCE(36);
      END_STATE();
    case 30:
      if (lookahead == 't') ADVANCE(37);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_list);
      END_STATE();
    case 32:
      if (lookahead == 'a') ADVANCE(38);
      END_STATE();
    case 33:
      if (lookahead == 'e') ADVANCE(39);
      END_STATE();
    case 34:
      if (lookahead == 'o') ADVANCE(40);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_wire);
      END_STATE();
    case 36:
      if (lookahead == 'a') ADVANCE(41);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_float);
      END_STATE();
    case 38:
      if (lookahead == 'l') ADVANCE(42);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_state);
      END_STATE();
    case 40:
      if (lookahead == 'l') ADVANCE(43);
      END_STATE();
    case 41:
      if (lookahead == 'c') ADVANCE(44);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_signal);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_symbol);
      END_STATE();
    case 44:
      if (lookahead == 'k') ADVANCE(45);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_feedback);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 7},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 7},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 8},
  [68] = {.lex_state = 7},
  [69] = {.lex_state = 1},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 8},
  [73] = {.lex_state = 1},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 1},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 1},
  [83] = {.lex_state = 9},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 1},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 1},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 7},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 1},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 1},
  [113] = {.lex_state = 7},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 1},
  [118] = {.lex_state = 1},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 9},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 7},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_plain_identifier] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_out] = ACTIONS(1),
    [anon_sym_signal] = ACTIONS(1),
    [anon_sym_float] = ACTIONS(1),
    [anon_sym_int] = ACTIONS(1),
    [anon_sym_bang] = ACTIONS(1),
    [anon_sym_list] = ACTIONS(1),
    [anon_sym_symbol] = ACTIONS(1),
    [anon_sym_wire] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_msg] = ACTIONS(1),
    [anon_sym_DOTattr_LPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_feedback] = ACTIONS(1),
    [anon_sym_state] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [aux_sym_number_token1] = ACTIONS(1),
    [aux_sym_number_token2] = ACTIONS(1),
    [aux_sym_number_token3] = ACTIONS(1),
    [aux_sym_number_token4] = ACTIONS(1),
    [aux_sym_number_token5] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(123),
    [sym__statement] = STATE(2),
    [sym_port_declaration] = STATE(2),
    [sym_direction] = STATE(64),
    [sym_destructuring_wire] = STATE(2),
    [sym_wire_declaration] = STATE(2),
    [sym_msg_declaration] = STATE(2),
    [sym_out_assignment] = STATE(2),
    [sym_direct_connection] = STATE(2),
    [sym_feedback_declaration] = STATE(2),
    [sym_feedback_assignment] = STATE(2),
    [sym_state_declaration] = STATE(2),
    [sym_state_assignment] = STATE(2),
    [sym_input_port_access] = STATE(92),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_plain_identifier] = ACTIONS(7),
    [anon_sym_in] = ACTIONS(9),
    [anon_sym_out] = ACTIONS(11),
    [anon_sym_wire] = ACTIONS(13),
    [anon_sym_msg] = ACTIONS(15),
    [anon_sym_feedback] = ACTIONS(17),
    [anon_sym_state] = ACTIONS(19),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_plain_identifier,
    ACTIONS(9), 1,
      anon_sym_in,
    ACTIONS(11), 1,
      anon_sym_out,
    ACTIONS(13), 1,
      anon_sym_wire,
    ACTIONS(15), 1,
      anon_sym_msg,
    ACTIONS(17), 1,
      anon_sym_feedback,
    ACTIONS(19), 1,
      anon_sym_state,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    STATE(64), 1,
      sym_direction,
    STATE(92), 1,
      sym_input_port_access,
    STATE(3), 12,
      sym__statement,
      sym_port_declaration,
      sym_destructuring_wire,
      sym_wire_declaration,
      sym_msg_declaration,
      sym_out_assignment,
      sym_direct_connection,
      sym_feedback_declaration,
      sym_feedback_assignment,
      sym_state_declaration,
      sym_state_assignment,
      aux_sym_source_file_repeat1,
  [48] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(25), 1,
      sym_plain_identifier,
    ACTIONS(28), 1,
      anon_sym_in,
    ACTIONS(31), 1,
      anon_sym_out,
    ACTIONS(34), 1,
      anon_sym_wire,
    ACTIONS(37), 1,
      anon_sym_msg,
    ACTIONS(40), 1,
      anon_sym_feedback,
    ACTIONS(43), 1,
      anon_sym_state,
    STATE(64), 1,
      sym_direction,
    STATE(92), 1,
      sym_input_port_access,
    STATE(3), 12,
      sym__statement,
      sym_port_declaration,
      sym_destructuring_wire,
      sym_wire_declaration,
      sym_msg_declaration,
      sym_out_assignment,
      sym_direct_connection,
      sym_feedback_declaration,
      sym_feedback_assignment,
      sym_state_declaration,
      sym_state_assignment,
      aux_sym_source_file_repeat1,
  [96] = 13,
    ACTIONS(46), 1,
      sym_plain_identifier,
    ACTIONS(48), 1,
      anon_sym_LPAREN,
    ACTIONS(50), 1,
      anon_sym_RPAREN,
    ACTIONS(52), 1,
      sym_operator_name,
    ACTIONS(54), 1,
      sym_tilde_identifier,
    ACTIONS(60), 1,
      sym_string,
    ACTIONS(62), 1,
      sym_comment,
    STATE(40), 1,
      sym_dotted_identifier,
    STATE(87), 1,
      sym_argument_list,
    STATE(106), 1,
      sym_object_name,
    ACTIONS(56), 2,
      aux_sym_number_token1,
      aux_sym_number_token2,
    ACTIONS(58), 3,
      aux_sym_number_token3,
      aux_sym_number_token4,
      aux_sym_number_token5,
    STATE(54), 6,
      sym_output_port_access,
      sym__expression,
      sym_tuple_expression,
      sym_object_call,
      sym_identifier,
      sym_number,
  [144] = 11,
    ACTIONS(48), 1,
      anon_sym_LPAREN,
    ACTIONS(52), 1,
      sym_operator_name,
    ACTIONS(54), 1,
      sym_tilde_identifier,
    ACTIONS(62), 1,
      sym_comment,
    ACTIONS(64), 1,
      sym_plain_identifier,
    ACTIONS(66), 1,
      sym_string,
    STATE(40), 1,
      sym_dotted_identifier,
    STATE(106), 1,
      sym_object_name,
    ACTIONS(56), 2,
      aux_sym_number_token1,
      aux_sym_number_token2,
    ACTIONS(58), 3,
      aux_sym_number_token3,
      aux_sym_number_token4,
      aux_sym_number_token5,
    STATE(61), 6,
      sym_output_port_access,
      sym__expression,
      sym_tuple_expression,
      sym_object_call,
      sym_identifier,
      sym_number,
  [186] = 11,
    ACTIONS(46), 1,
      sym_plain_identifier,
    ACTIONS(48), 1,
      anon_sym_LPAREN,
    ACTIONS(52), 1,
      sym_operator_name,
    ACTIONS(54), 1,
      sym_tilde_identifier,
    ACTIONS(62), 1,
      sym_comment,
    ACTIONS(68), 1,
      sym_string,
    STATE(40), 1,
      sym_dotted_identifier,
    STATE(106), 1,
      sym_object_name,
    ACTIONS(56), 2,
      aux_sym_number_token1,
      aux_sym_number_token2,
    ACTIONS(58), 3,
      aux_sym_number_token3,
      aux_sym_number_token4,
      aux_sym_number_token5,
    STATE(105), 6,
      sym_output_port_access,
      sym__expression,
      sym_tuple_expression,
      sym_object_call,
      sym_identifier,
      sym_number,
  [228] = 11,
    ACTIONS(46), 1,
      sym_plain_identifier,
    ACTIONS(48), 1,
      anon_sym_LPAREN,
    ACTIONS(52), 1,
      sym_operator_name,
    ACTIONS(54), 1,
      sym_tilde_identifier,
    ACTIONS(62), 1,
      sym_comment,
    ACTIONS(70), 1,
      sym_string,
    STATE(40), 1,
      sym_dotted_identifier,
    STATE(106), 1,
      sym_object_name,
    ACTIONS(56), 2,
      aux_sym_number_token1,
      aux_sym_number_token2,
    ACTIONS(58), 3,
      aux_sym_number_token3,
      aux_sym_number_token4,
      aux_sym_number_token5,
    STATE(63), 6,
      sym_output_port_access,
      sym__expression,
      sym_tuple_expression,
      sym_object_call,
      sym_identifier,
      sym_number,
  [270] = 11,
    ACTIONS(46), 1,
      sym_plain_identifier,
    ACTIONS(48), 1,
      anon_sym_LPAREN,
    ACTIONS(52), 1,
      sym_operator_name,
    ACTIONS(54), 1,
      sym_tilde_identifier,
    ACTIONS(62), 1,
      sym_comment,
    ACTIONS(72), 1,
      sym_string,
    STATE(40), 1,
      sym_dotted_identifier,
    STATE(106), 1,
      sym_object_name,
    ACTIONS(56), 2,
      aux_sym_number_token1,
      aux_sym_number_token2,
    ACTIONS(58), 3,
      aux_sym_number_token3,
      aux_sym_number_token4,
      aux_sym_number_token5,
    STATE(86), 6,
      sym_output_port_access,
      sym__expression,
      sym_tuple_expression,
      sym_object_call,
      sym_identifier,
      sym_number,
  [312] = 11,
    ACTIONS(46), 1,
      sym_plain_identifier,
    ACTIONS(48), 1,
      anon_sym_LPAREN,
    ACTIONS(52), 1,
      sym_operator_name,
    ACTIONS(54), 1,
      sym_tilde_identifier,
    ACTIONS(62), 1,
      sym_comment,
    ACTIONS(74), 1,
      sym_string,
    STATE(40), 1,
      sym_dotted_identifier,
    STATE(106), 1,
      sym_object_name,
    ACTIONS(56), 2,
      aux_sym_number_token1,
      aux_sym_number_token2,
    ACTIONS(58), 3,
      aux_sym_number_token3,
      aux_sym_number_token4,
      aux_sym_number_token5,
    STATE(88), 6,
      sym_output_port_access,
      sym__expression,
      sym_tuple_expression,
      sym_object_call,
      sym_identifier,
      sym_number,
  [354] = 11,
    ACTIONS(46), 1,
      sym_plain_identifier,
    ACTIONS(48), 1,
      anon_sym_LPAREN,
    ACTIONS(52), 1,
      sym_operator_name,
    ACTIONS(54), 1,
      sym_tilde_identifier,
    ACTIONS(62), 1,
      sym_comment,
    ACTIONS(76), 1,
      sym_string,
    STATE(40), 1,
      sym_dotted_identifier,
    STATE(106), 1,
      sym_object_name,
    ACTIONS(56), 2,
      aux_sym_number_token1,
      aux_sym_number_token2,
    ACTIONS(58), 3,
      aux_sym_number_token3,
      aux_sym_number_token4,
      aux_sym_number_token5,
    STATE(89), 6,
      sym_output_port_access,
      sym__expression,
      sym_tuple_expression,
      sym_object_call,
      sym_identifier,
      sym_number,
  [396] = 11,
    ACTIONS(46), 1,
      sym_plain_identifier,
    ACTIONS(48), 1,
      anon_sym_LPAREN,
    ACTIONS(52), 1,
      sym_operator_name,
    ACTIONS(54), 1,
      sym_tilde_identifier,
    ACTIONS(62), 1,
      sym_comment,
    ACTIONS(78), 1,
      sym_string,
    STATE(40), 1,
      sym_dotted_identifier,
    STATE(106), 1,
      sym_object_name,
    ACTIONS(56), 2,
      aux_sym_number_token1,
      aux_sym_number_token2,
    ACTIONS(58), 3,
      aux_sym_number_token3,
      aux_sym_number_token4,
      aux_sym_number_token5,
    STATE(127), 6,
      sym_output_port_access,
      sym__expression,
      sym_tuple_expression,
      sym_object_call,
      sym_identifier,
      sym_number,
  [438] = 11,
    ACTIONS(46), 1,
      sym_plain_identifier,
    ACTIONS(48), 1,
      anon_sym_LPAREN,
    ACTIONS(52), 1,
      sym_operator_name,
    ACTIONS(54), 1,
      sym_tilde_identifier,
    ACTIONS(62), 1,
      sym_comment,
    ACTIONS(80), 1,
      sym_string,
    STATE(40), 1,
      sym_dotted_identifier,
    STATE(106), 1,
      sym_object_name,
    ACTIONS(56), 2,
      aux_sym_number_token1,
      aux_sym_number_token2,
    ACTIONS(58), 3,
      aux_sym_number_token3,
      aux_sym_number_token4,
      aux_sym_number_token5,
    STATE(95), 6,
      sym_output_port_access,
      sym__expression,
      sym_tuple_expression,
      sym_object_call,
      sym_identifier,
      sym_number,
  [480] = 11,
    ACTIONS(46), 1,
      sym_plain_identifier,
    ACTIONS(48), 1,
      anon_sym_LPAREN,
    ACTIONS(52), 1,
      sym_operator_name,
    ACTIONS(54), 1,
      sym_tilde_identifier,
    ACTIONS(62), 1,
      sym_comment,
    ACTIONS(82), 1,
      sym_string,
    STATE(40), 1,
      sym_dotted_identifier,
    STATE(106), 1,
      sym_object_name,
    ACTIONS(56), 2,
      aux_sym_number_token1,
      aux_sym_number_token2,
    ACTIONS(58), 3,
      aux_sym_number_token3,
      aux_sym_number_token4,
      aux_sym_number_token5,
    STATE(97), 6,
      sym_output_port_access,
      sym__expression,
      sym_tuple_expression,
      sym_object_call,
      sym_identifier,
      sym_number,
  [522] = 11,
    ACTIONS(46), 1,
      sym_plain_identifier,
    ACTIONS(48), 1,
      anon_sym_LPAREN,
    ACTIONS(52), 1,
      sym_operator_name,
    ACTIONS(54), 1,
      sym_tilde_identifier,
    ACTIONS(62), 1,
      sym_comment,
    ACTIONS(84), 1,
      sym_string,
    STATE(40), 1,
      sym_dotted_identifier,
    STATE(106), 1,
      sym_object_name,
    ACTIONS(56), 2,
      aux_sym_number_token1,
      aux_sym_number_token2,
    ACTIONS(58), 3,
      aux_sym_number_token3,
      aux_sym_number_token4,
      aux_sym_number_token5,
    STATE(78), 6,
      sym_output_port_access,
      sym__expression,
      sym_tuple_expression,
      sym_object_call,
      sym_identifier,
      sym_number,
  [564] = 11,
    ACTIONS(46), 1,
      sym_plain_identifier,
    ACTIONS(48), 1,
      anon_sym_LPAREN,
    ACTIONS(52), 1,
      sym_operator_name,
    ACTIONS(54), 1,
      sym_tilde_identifier,
    ACTIONS(62), 1,
      sym_comment,
    ACTIONS(86), 1,
      sym_string,
    STATE(40), 1,
      sym_dotted_identifier,
    STATE(106), 1,
      sym_object_name,
    ACTIONS(56), 2,
      aux_sym_number_token1,
      aux_sym_number_token2,
    ACTIONS(58), 3,
      aux_sym_number_token3,
      aux_sym_number_token4,
      aux_sym_number_token5,
    STATE(121), 6,
      sym_output_port_access,
      sym__expression,
      sym_tuple_expression,
      sym_object_call,
      sym_identifier,
      sym_number,
  [606] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 2,
      aux_sym_number_token1,
      aux_sym_number_token2,
    ACTIONS(88), 2,
      sym_plain_identifier,
      sym_string,
    STATE(76), 2,
      sym__attr_value,
      sym_number,
    ACTIONS(58), 3,
      aux_sym_number_token3,
      aux_sym_number_token4,
      aux_sym_number_token5,
  [627] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 1,
      ts_builtin_sym_end,
    ACTIONS(92), 7,
      anon_sym_in,
      anon_sym_out,
      anon_sym_wire,
      anon_sym_msg,
      anon_sym_feedback,
      anon_sym_state,
      sym_plain_identifier,
  [643] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 1,
      ts_builtin_sym_end,
    ACTIONS(96), 7,
      anon_sym_in,
      anon_sym_out,
      anon_sym_wire,
      anon_sym_msg,
      anon_sym_feedback,
      anon_sym_state,
      sym_plain_identifier,
  [659] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 1,
      ts_builtin_sym_end,
    ACTIONS(100), 7,
      anon_sym_in,
      anon_sym_out,
      anon_sym_wire,
      anon_sym_msg,
      anon_sym_feedback,
      anon_sym_state,
      sym_plain_identifier,
  [675] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 1,
      ts_builtin_sym_end,
    ACTIONS(104), 7,
      anon_sym_in,
      anon_sym_out,
      anon_sym_wire,
      anon_sym_msg,
      anon_sym_feedback,
      anon_sym_state,
      sym_plain_identifier,
  [691] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 1,
      ts_builtin_sym_end,
    ACTIONS(108), 7,
      anon_sym_in,
      anon_sym_out,
      anon_sym_wire,
      anon_sym_msg,
      anon_sym_feedback,
      anon_sym_state,
      sym_plain_identifier,
  [707] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 1,
      ts_builtin_sym_end,
    ACTIONS(112), 7,
      anon_sym_in,
      anon_sym_out,
      anon_sym_wire,
      anon_sym_msg,
      anon_sym_feedback,
      anon_sym_state,
      sym_plain_identifier,
  [723] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      ts_builtin_sym_end,
    ACTIONS(116), 7,
      anon_sym_in,
      anon_sym_out,
      anon_sym_wire,
      anon_sym_msg,
      anon_sym_feedback,
      anon_sym_state,
      sym_plain_identifier,
  [739] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 1,
      ts_builtin_sym_end,
    ACTIONS(120), 7,
      anon_sym_in,
      anon_sym_out,
      anon_sym_wire,
      anon_sym_msg,
      anon_sym_feedback,
      anon_sym_state,
      sym_plain_identifier,
  [755] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 1,
      ts_builtin_sym_end,
    ACTIONS(124), 7,
      anon_sym_in,
      anon_sym_out,
      anon_sym_wire,
      anon_sym_msg,
      anon_sym_feedback,
      anon_sym_state,
      sym_plain_identifier,
  [771] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 1,
      ts_builtin_sym_end,
    ACTIONS(128), 7,
      anon_sym_in,
      anon_sym_out,
      anon_sym_wire,
      anon_sym_msg,
      anon_sym_feedback,
      anon_sym_state,
      sym_plain_identifier,
  [787] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 1,
      ts_builtin_sym_end,
    ACTIONS(132), 7,
      anon_sym_in,
      anon_sym_out,
      anon_sym_wire,
      anon_sym_msg,
      anon_sym_feedback,
      anon_sym_state,
      sym_plain_identifier,
  [803] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 1,
      ts_builtin_sym_end,
    ACTIONS(136), 7,
      anon_sym_in,
      anon_sym_out,
      anon_sym_wire,
      anon_sym_msg,
      anon_sym_feedback,
      anon_sym_state,
      sym_plain_identifier,
  [819] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 1,
      ts_builtin_sym_end,
    ACTIONS(140), 7,
      anon_sym_in,
      anon_sym_out,
      anon_sym_wire,
      anon_sym_msg,
      anon_sym_feedback,
      anon_sym_state,
      sym_plain_identifier,
  [835] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 1,
      ts_builtin_sym_end,
    ACTIONS(144), 7,
      anon_sym_in,
      anon_sym_out,
      anon_sym_wire,
      anon_sym_msg,
      anon_sym_feedback,
      anon_sym_state,
      sym_plain_identifier,
  [851] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 1,
      ts_builtin_sym_end,
    ACTIONS(148), 7,
      anon_sym_in,
      anon_sym_out,
      anon_sym_wire,
      anon_sym_msg,
      anon_sym_feedback,
      anon_sym_state,
      sym_plain_identifier,
  [867] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(66), 1,
      sym_type_name,
    ACTIONS(150), 6,
      anon_sym_signal,
      anon_sym_float,
      anon_sym_int,
      anon_sym_bang,
      anon_sym_list,
      anon_sym_symbol,
  [882] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(125), 1,
      sym_type_name,
    ACTIONS(150), 6,
      anon_sym_signal,
      anon_sym_float,
      anon_sym_int,
      anon_sym_bang,
      anon_sym_list,
      anon_sym_symbol,
  [897] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(75), 1,
      sym_type_name,
    ACTIONS(150), 6,
      anon_sym_signal,
      anon_sym_float,
      anon_sym_int,
      anon_sym_bang,
      anon_sym_list,
      anon_sym_symbol,
  [912] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 1,
      anon_sym_LPAREN,
    ACTIONS(156), 1,
      anon_sym_DOT,
    STATE(36), 1,
      aux_sym_dotted_identifier_repeat1,
    ACTIONS(154), 3,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
  [930] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 1,
      anon_sym_DOT,
    STATE(38), 1,
      aux_sym_dotted_identifier_repeat1,
    ACTIONS(158), 4,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
  [946] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(128), 1,
      sym_control_type,
    ACTIONS(162), 5,
      anon_sym_float,
      anon_sym_int,
      anon_sym_bang,
      anon_sym_list,
      anon_sym_symbol,
  [960] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(166), 1,
      anon_sym_DOT,
    STATE(38), 1,
      aux_sym_dotted_identifier_repeat1,
    ACTIONS(164), 4,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
  [976] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 1,
      anon_sym_DOT,
    STATE(39), 1,
      aux_sym_dotted_identifier_repeat1,
    ACTIONS(164), 3,
      anon_sym_LPAREN,
      anon_sym_SEMI,
      anon_sym_DOTattr_LPAREN,
  [991] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 4,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_DOTattr_LPAREN,
  [1004] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 5,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_DOT,
  [1015] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 1,
      anon_sym_LPAREN,
    ACTIONS(172), 1,
      anon_sym_DOT,
    STATE(43), 1,
      aux_sym_dotted_identifier_repeat1,
    ACTIONS(154), 2,
      anon_sym_SEMI,
      anon_sym_DOTattr_LPAREN,
  [1032] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 1,
      anon_sym_DOT,
    STATE(39), 1,
      aux_sym_dotted_identifier_repeat1,
    ACTIONS(158), 3,
      anon_sym_LPAREN,
      anon_sym_SEMI,
      anon_sym_DOTattr_LPAREN,
  [1047] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 4,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_DOTattr_LPAREN,
  [1057] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 4,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_DOTattr_LPAREN,
  [1067] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 4,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_DOTattr_LPAREN,
  [1077] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 4,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_DOTattr_LPAREN,
  [1087] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 4,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_DOTattr_LPAREN,
  [1097] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      anon_sym_DOT,
    ACTIONS(164), 3,
      anon_sym_LPAREN,
      anon_sym_SEMI,
      anon_sym_DOTattr_LPAREN,
  [1109] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 1,
      anon_sym_RPAREN,
    ACTIONS(190), 1,
      anon_sym_COMMA,
    STATE(58), 1,
      aux_sym_tuple_expression_repeat1,
  [1122] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(194), 1,
      anon_sym_LBRACK,
    ACTIONS(192), 2,
      sym_plain_identifier,
      sym_integer,
  [1133] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 1,
      anon_sym_RPAREN,
    ACTIONS(198), 1,
      anon_sym_COMMA,
    STATE(52), 1,
      aux_sym_identifier_list_repeat1,
  [1146] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 1,
      sym_plain_identifier,
    STATE(55), 1,
      sym_attr_pair,
    STATE(91), 1,
      sym_attr_list,
  [1159] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(190), 1,
      anon_sym_COMMA,
    ACTIONS(203), 1,
      anon_sym_RPAREN,
    STATE(59), 1,
      aux_sym_tuple_expression_repeat1,
  [1172] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 1,
      anon_sym_RPAREN,
    ACTIONS(207), 1,
      anon_sym_COMMA,
    STATE(60), 1,
      aux_sym_attr_list_repeat1,
  [1185] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 1,
      anon_sym_RPAREN,
    ACTIONS(211), 1,
      anon_sym_COMMA,
    STATE(52), 1,
      aux_sym_identifier_list_repeat1,
  [1198] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 1,
      anon_sym_RPAREN,
    ACTIONS(215), 1,
      anon_sym_COMMA,
    STATE(57), 1,
      aux_sym_attr_list_repeat1,
  [1211] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(218), 1,
      anon_sym_RPAREN,
    ACTIONS(220), 1,
      anon_sym_COMMA,
    STATE(58), 1,
      aux_sym_tuple_expression_repeat1,
  [1224] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(190), 1,
      anon_sym_COMMA,
    ACTIONS(223), 1,
      anon_sym_RPAREN,
    STATE(58), 1,
      aux_sym_tuple_expression_repeat1,
  [1237] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 1,
      anon_sym_COMMA,
    ACTIONS(225), 1,
      anon_sym_RPAREN,
    STATE(57), 1,
      aux_sym_attr_list_repeat1,
  [1250] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 1,
      anon_sym_SEMI,
    ACTIONS(229), 1,
      anon_sym_DOTattr_LPAREN,
    STATE(101), 1,
      sym_attr_chain,
  [1263] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(229), 1,
      anon_sym_DOTattr_LPAREN,
    ACTIONS(231), 1,
      anon_sym_SEMI,
    STATE(104), 1,
      sym_attr_chain,
  [1276] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(190), 1,
      anon_sym_COMMA,
    STATE(50), 1,
      aux_sym_tuple_expression_repeat1,
  [1286] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 1,
      sym_plain_identifier,
    ACTIONS(235), 1,
      sym_integer,
  [1296] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1304] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 1,
      anon_sym_EQ,
    ACTIONS(239), 1,
      anon_sym_SEMI,
  [1314] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 1,
      anon_sym_out,
    ACTIONS(243), 1,
      sym_dotted_segment,
  [1324] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(192), 2,
      sym_plain_identifier,
      sym_integer,
  [1332] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 1,
      sym_plain_identifier,
    STATE(109), 1,
      sym_identifier_list,
  [1342] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 1,
      anon_sym_COLON,
    ACTIONS(249), 1,
      anon_sym_EQ,
  [1352] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      anon_sym_EQ,
    ACTIONS(253), 1,
      anon_sym_LBRACK,
  [1362] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 1,
      anon_sym_out,
    ACTIONS(255), 1,
      sym_dotted_segment,
  [1372] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 1,
      sym_plain_identifier,
    STATE(77), 1,
      sym_attr_pair,
  [1382] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 1,
      anon_sym_COMMA,
    STATE(56), 1,
      aux_sym_identifier_list_repeat1,
  [1392] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 1,
      anon_sym_EQ,
    ACTIONS(259), 1,
      anon_sym_SEMI,
  [1402] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1410] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1418] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(218), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1426] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(263), 1,
      anon_sym_COLON,
    ACTIONS(265), 1,
      anon_sym_EQ,
  [1436] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(267), 1,
      sym_plain_identifier,
    ACTIONS(269), 1,
      anon_sym_LPAREN,
  [1446] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(271), 2,
      anon_sym_EQ,
      anon_sym_SEMI,
  [1454] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(273), 1,
      anon_sym_DOT,
  [1461] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(275), 1,
      sym_dotted_segment,
  [1468] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 1,
      anon_sym_RPAREN,
  [1475] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(279), 1,
      sym_plain_identifier,
  [1482] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(281), 1,
      anon_sym_SEMI,
  [1489] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 1,
      anon_sym_RPAREN,
  [1496] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(285), 1,
      anon_sym_SEMI,
  [1503] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(287), 1,
      anon_sym_SEMI,
  [1510] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(289), 1,
      anon_sym_COLON,
  [1517] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(291), 1,
      anon_sym_RPAREN,
  [1524] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(293), 1,
      anon_sym_EQ,
  [1531] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(295), 1,
      anon_sym_in,
  [1538] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 1,
      anon_sym_LPAREN,
  [1545] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(297), 1,
      anon_sym_SEMI,
  [1552] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(299), 1,
      anon_sym_EQ,
  [1559] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(301), 1,
      anon_sym_SEMI,
  [1566] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(303), 1,
      sym_string,
  [1573] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(305), 1,
      sym_integer,
  [1580] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(307), 1,
      anon_sym_RBRACK,
  [1587] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(309), 1,
      anon_sym_SEMI,
  [1594] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(311), 1,
      anon_sym_EQ,
  [1601] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(313), 1,
      anon_sym_COLON,
  [1608] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(315), 1,
      anon_sym_SEMI,
  [1615] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(317), 1,
      anon_sym_SEMI,
  [1622] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(319), 1,
      anon_sym_LPAREN,
  [1629] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(321), 1,
      anon_sym_EQ,
  [1636] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(323), 1,
      anon_sym_SEMI,
  [1643] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(325), 1,
      anon_sym_RPAREN,
  [1650] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(327), 1,
      sym_plain_identifier,
  [1657] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(329), 1,
      anon_sym_EQ,
  [1664] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(331), 1,
      sym_plain_identifier,
  [1671] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(333), 1,
      sym_integer,
  [1678] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(335), 1,
      anon_sym_RBRACK,
  [1685] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(337), 1,
      anon_sym_LPAREN,
  [1692] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(339), 1,
      anon_sym_RBRACK,
  [1699] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(341), 1,
      sym_plain_identifier,
  [1706] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(343), 1,
      sym_plain_identifier,
  [1713] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(345), 1,
      anon_sym_COLON,
  [1720] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(347), 1,
      anon_sym_EQ,
  [1727] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(349), 1,
      anon_sym_SEMI,
  [1734] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(351), 1,
      anon_sym_EQ,
  [1741] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(353), 1,
      ts_builtin_sym_end,
  [1748] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(355), 1,
      anon_sym_LBRACK,
  [1755] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(357), 1,
      anon_sym_SEMI,
  [1762] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(359), 1,
      sym_dotted_segment,
  [1769] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(361), 1,
      anon_sym_SEMI,
  [1776] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(363), 1,
      anon_sym_EQ,
  [1783] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(365), 1,
      sym_integer,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 48,
  [SMALL_STATE(4)] = 96,
  [SMALL_STATE(5)] = 144,
  [SMALL_STATE(6)] = 186,
  [SMALL_STATE(7)] = 228,
  [SMALL_STATE(8)] = 270,
  [SMALL_STATE(9)] = 312,
  [SMALL_STATE(10)] = 354,
  [SMALL_STATE(11)] = 396,
  [SMALL_STATE(12)] = 438,
  [SMALL_STATE(13)] = 480,
  [SMALL_STATE(14)] = 522,
  [SMALL_STATE(15)] = 564,
  [SMALL_STATE(16)] = 606,
  [SMALL_STATE(17)] = 627,
  [SMALL_STATE(18)] = 643,
  [SMALL_STATE(19)] = 659,
  [SMALL_STATE(20)] = 675,
  [SMALL_STATE(21)] = 691,
  [SMALL_STATE(22)] = 707,
  [SMALL_STATE(23)] = 723,
  [SMALL_STATE(24)] = 739,
  [SMALL_STATE(25)] = 755,
  [SMALL_STATE(26)] = 771,
  [SMALL_STATE(27)] = 787,
  [SMALL_STATE(28)] = 803,
  [SMALL_STATE(29)] = 819,
  [SMALL_STATE(30)] = 835,
  [SMALL_STATE(31)] = 851,
  [SMALL_STATE(32)] = 867,
  [SMALL_STATE(33)] = 882,
  [SMALL_STATE(34)] = 897,
  [SMALL_STATE(35)] = 912,
  [SMALL_STATE(36)] = 930,
  [SMALL_STATE(37)] = 946,
  [SMALL_STATE(38)] = 960,
  [SMALL_STATE(39)] = 976,
  [SMALL_STATE(40)] = 991,
  [SMALL_STATE(41)] = 1004,
  [SMALL_STATE(42)] = 1015,
  [SMALL_STATE(43)] = 1032,
  [SMALL_STATE(44)] = 1047,
  [SMALL_STATE(45)] = 1057,
  [SMALL_STATE(46)] = 1067,
  [SMALL_STATE(47)] = 1077,
  [SMALL_STATE(48)] = 1087,
  [SMALL_STATE(49)] = 1097,
  [SMALL_STATE(50)] = 1109,
  [SMALL_STATE(51)] = 1122,
  [SMALL_STATE(52)] = 1133,
  [SMALL_STATE(53)] = 1146,
  [SMALL_STATE(54)] = 1159,
  [SMALL_STATE(55)] = 1172,
  [SMALL_STATE(56)] = 1185,
  [SMALL_STATE(57)] = 1198,
  [SMALL_STATE(58)] = 1211,
  [SMALL_STATE(59)] = 1224,
  [SMALL_STATE(60)] = 1237,
  [SMALL_STATE(61)] = 1250,
  [SMALL_STATE(62)] = 1263,
  [SMALL_STATE(63)] = 1276,
  [SMALL_STATE(64)] = 1286,
  [SMALL_STATE(65)] = 1296,
  [SMALL_STATE(66)] = 1304,
  [SMALL_STATE(67)] = 1314,
  [SMALL_STATE(68)] = 1324,
  [SMALL_STATE(69)] = 1332,
  [SMALL_STATE(70)] = 1342,
  [SMALL_STATE(71)] = 1352,
  [SMALL_STATE(72)] = 1362,
  [SMALL_STATE(73)] = 1372,
  [SMALL_STATE(74)] = 1382,
  [SMALL_STATE(75)] = 1392,
  [SMALL_STATE(76)] = 1402,
  [SMALL_STATE(77)] = 1410,
  [SMALL_STATE(78)] = 1418,
  [SMALL_STATE(79)] = 1426,
  [SMALL_STATE(80)] = 1436,
  [SMALL_STATE(81)] = 1446,
  [SMALL_STATE(82)] = 1454,
  [SMALL_STATE(83)] = 1461,
  [SMALL_STATE(84)] = 1468,
  [SMALL_STATE(85)] = 1475,
  [SMALL_STATE(86)] = 1482,
  [SMALL_STATE(87)] = 1489,
  [SMALL_STATE(88)] = 1496,
  [SMALL_STATE(89)] = 1503,
  [SMALL_STATE(90)] = 1510,
  [SMALL_STATE(91)] = 1517,
  [SMALL_STATE(92)] = 1524,
  [SMALL_STATE(93)] = 1531,
  [SMALL_STATE(94)] = 1538,
  [SMALL_STATE(95)] = 1545,
  [SMALL_STATE(96)] = 1552,
  [SMALL_STATE(97)] = 1559,
  [SMALL_STATE(98)] = 1566,
  [SMALL_STATE(99)] = 1573,
  [SMALL_STATE(100)] = 1580,
  [SMALL_STATE(101)] = 1587,
  [SMALL_STATE(102)] = 1594,
  [SMALL_STATE(103)] = 1601,
  [SMALL_STATE(104)] = 1608,
  [SMALL_STATE(105)] = 1615,
  [SMALL_STATE(106)] = 1622,
  [SMALL_STATE(107)] = 1629,
  [SMALL_STATE(108)] = 1636,
  [SMALL_STATE(109)] = 1643,
  [SMALL_STATE(110)] = 1650,
  [SMALL_STATE(111)] = 1657,
  [SMALL_STATE(112)] = 1664,
  [SMALL_STATE(113)] = 1671,
  [SMALL_STATE(114)] = 1678,
  [SMALL_STATE(115)] = 1685,
  [SMALL_STATE(116)] = 1692,
  [SMALL_STATE(117)] = 1699,
  [SMALL_STATE(118)] = 1706,
  [SMALL_STATE(119)] = 1713,
  [SMALL_STATE(120)] = 1720,
  [SMALL_STATE(121)] = 1727,
  [SMALL_STATE(122)] = 1734,
  [SMALL_STATE(123)] = 1741,
  [SMALL_STATE(124)] = 1748,
  [SMALL_STATE(125)] = 1755,
  [SMALL_STATE(126)] = 1762,
  [SMALL_STATE(127)] = 1769,
  [SMALL_STATE(128)] = 1776,
  [SMALL_STATE(129)] = 1783,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(117),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(110),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(118),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(82),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(80),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(117),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(110),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(118),
  [46] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [52] = {.entry = {.count = 1, .reusable = false}}, SHIFT(94),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [58] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [62] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_feedback_declaration, 5, 0, 5),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_feedback_declaration, 5, 0, 5),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_state_assignment, 5, 0, 6),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_state_assignment, 5, 0, 6),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_msg_declaration, 5, 0, 4),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_msg_declaration, 5, 0, 4),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_wire_declaration, 5, 0, 3),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_wire_declaration, 5, 0, 3),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_direct_connection, 4, 0, 2),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_direct_connection, 4, 0, 2),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_feedback_assignment, 5, 0, 6),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_feedback_assignment, 5, 0, 6),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_port_declaration, 5, 0, 7),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_port_declaration, 5, 0, 7),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_port_declaration, 10, 0, 19),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_port_declaration, 10, 0, 19),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_wire_declaration, 6, 0, 8),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_wire_declaration, 6, 0, 8),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_msg_declaration, 6, 0, 9),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_msg_declaration, 6, 0, 9),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_destructuring_wire, 7, 0, 13),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_destructuring_wire, 7, 0, 13),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_out_assignment, 7, 0, 12),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_out_assignment, 7, 0, 12),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_port_declaration, 8, 0, 18),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_port_declaration, 8, 0, 18),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_state_declaration, 7, 0, 15),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_state_declaration, 7, 0, 15),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_port_declaration, 7, 0, 16),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_port_declaration, 7, 0, 16),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_name, 1, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dotted_identifier, 2, -1, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_dotted_identifier_repeat1, 2, 0, 0),
  [166] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dotted_identifier_repeat1, 2, 0, 0), SHIFT_REPEAT(83),
  [169] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_dotted_identifier_repeat1, 2, 0, 0), SHIFT_REPEAT(126),
  [172] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [174] = {.entry = {.count = 1, .reusable = false}}, SHIFT(126),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_expression, 4, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_call, 4, 0, 11),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_output_port_access, 6, 10, 10),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_call, 3, 0, 1),
  [186] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_dotted_identifier_repeat1, 2, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_direction, 1, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_identifier_list_repeat1, 2, 0, 0),
  [198] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_identifier_list_repeat1, 2, 0, 0), SHIFT_REPEAT(112),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 1, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attr_list, 1, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier_list, 2, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_attr_list_repeat1, 2, 0, 0),
  [215] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_attr_list_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tuple_expression_repeat1, 2, 0, 0),
  [220] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tuple_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 2, 0, 0),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attr_list, 2, 0, 0),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [241] = {.entry = {.count = 1, .reusable = false}}, SHIFT(124),
  [243] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_input_port_access, 3, 10, 1),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [255] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [261] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attr_pair, 3, 0, 17),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [271] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_name, 1, 0, 0),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [299] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_input_port_access, 6, 10, 10),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [311] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_control_type, 1, 0, 0),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [323] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attr_chain, 3, 0, 14),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [353] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [361] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [363] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_flutmax(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_plain_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "flutmax",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
